
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'

export const POST_LIST_PENDING = 'POST_LIST_PENDING'

export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'

export const POST_COMMENT_PENDING = 'POST_COMMENT_PENDING'

export const COMMENT_VOTE_UP = 'COMMENT_VOTE_UP'

export const COMMENT_VOTE_DOWN = 'COMMENT_VOTE_DOWN'

export const POST_VOTE_UP = 'POST_VOTE_UP'

export const POST_VOTE_DOWN = 'POST_VOTE_DOWN'

export const POST_DETAIL_VOTE_UP = 'POST_DETAIL_VOTE_UP'

export const POST_DETAIL_VOTE_DOWN = 'POST_DETAIL_VOTE_DOWN'

export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS'

export const POST_DETAIL_PENDING = 'POST_DETAIL_PENDING'

export const COMMENT_EDIT_SUCCESS = 'COMMENT_EDIT_SUCCESS'

export const COMMENT_EDIT_PENDING = 'COMMENT_EDIT_PENDING'

export const POST_CATEGORY_LIST = 'POST_CATEGORY_LIST'

export const SORT_BY_SCORE = 'SORT_BY_SCORE'

export const COMMENTS_LIST_SUCCESS = 'COMMENTS_LIST_SUCCESS'

export const COMMENTS_LIST_PENDING = 'COMMENTS_LIST_PENDING'

export const POST_ADD = 'POST_ADD'

export const EDIT_PENDING = 'EDIT_PENDING'

export const EDIT_SUCCESS = 'EDIT_SUCCESS'

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'

export const DELETE_POST_PENDING = 'DELETE_POST_PENDING'